spring.application.name=vis-writingwebapp

#MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/visWebApp_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=AntumbraMai@69
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop